
name: test

on:
  # Triggers the workflow on push or pull request events but only for the "qa2" branch
  push:
    branches: ["test"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:alpine

    steps:
     - name: Setup git
       run: |
          echo "workspace is set to $GITHUB_WORKSPACE"
          apk add -q --no-cache --no-progress git yq tar
          git config --global --add safe.directory $GITHUB_WORKSPACE
     - name: Check out repository code
       uses: actions/checkout@v2
#      - id: cache-path
#        run: | 
#           echo "::set-output name=dir::$(mvn help:evaluate -Dexpression=settings.localRepository | grep 'm2/repository')"
     - name: Cache os release
       id: cache
       uses: actions/cache@v3
        with:
          path: |
            /etc/os-release
          key: test
      - if: steps.cache.outputs.cache-hit != 'true'
        name: Run liquibase update
        run: |
          pwd
          echo "current repo"
          ls
          echo "home path contents"
          ls -a /github/home/
